<?php
	$year = date('Y');
	$prev_year = $year - 1;
?>

<h2 id="glyphicons-glyphs">Annual Budget</h2>

<div class="panel-group" role="tablist" aria-multiselectable="true">
	<div class="panel panel-default">
		<div class="panel-body">
			<ul class="nav nav-tabs">
				<li class="active nav-danger"><a data-toggle="tab" href="#budgetPercentage">Unfinalised Budget Percentage</a></li>
				<li class="nav-warning"><a data-toggle="tab" href="#forVerification">For Verification</a></li>
				<li class="nav-info"><a data-toggle="tab" href="#forFinalApproval">For Final Approval</a></li>
				<li class="nav-success"><a data-toggle="tab" href="#approvedBudget">Approved Budget</a></li>
				<!--li class="nav-primary"><a data-toggle="tab" href="#forPurchase">For Purchase</a></li-->
				<a href="<?php echo HTTP_PATH.'budget/set_increment'; ?>" data-toggle="modal" data-target="#modalDialogNorm" data-backdrop="static">
					<button class="btn btn-primary btn-sm pull-right">Set Increment</button>
				</a>
			</ul>
			<div class="tab-content">
				<div id="budgetPercentage" class="tab-pane fade in active" >
					<table data-toggle="table" id="percentage-table" class="table table-bordered table-striped table-hover" data-url="<?php echo HTTP_PATH."budget/budget_percentage"; ?>" data-cache="false" data-side-pagination="server" data-pagination="true" data-show-columns="true" data-page-list="[5, 10, 20, 50, 100, 200, 500, 1000, 2500, 5000, 10000]" data-search="true" data-strict-search="false">
						<thead>
							<tr>
								<th data-field="id" data-align="center" data-visible="false" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">ID</th>
								<th data-field="code" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Code</th>
								<th data-field="account_name" data-align="center" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Account Name</th>
								<th data-field="percentage" data-align="center" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Increment %</th>
								<th data-field="updator" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Updated by</th>
								<th data-field="updated_on" data-align="center" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Updated on</th>
								<th data-field="operate" data-formatter="view" data-events="operateEvents"  data-halign="center" data-align="center">Manage</th>
							</tr>
						</thead>
					</table>
				</div>
				<div id="forVerification" class="tab-pane fade">
					<table data-toggle="table" id="for-verification-table" class="table table-bordered table-striped table-hover" data-url="<?php echo HTTP_PATH."budget/verify_budget_summary/for_verification"; ?>" data-cache="false" data-side-pagination="server" data-pagination="true" data-show-columns="true" data-page-list="[5, 10, 20, 50, 100, 200, 500, 1000, 2500, 5000, 10000]" data-search="true" data-strict-search="false">
						<thead>
							<tr>
								<th data-field="id" data-align="center" data-visible="false" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">ID</th>
								<th data-field="company" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Company</th>
								<th data-field="department" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Department</th>
								<th data-field="vessel" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Vessel</th>
								<th data-field="status" data-align="center" data-visible="false" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Status</th>
								<th data-field="final_amount" data-align="center" data-visible="false" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Total Amount</th>
								<th data-field="type" data-align="center" data-visible="false" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Type</th>
								<th data-field="year" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Year</th>
								<th data-field="generated_by" data-align="center" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Generated by</th>
								<th data-field="generated_on" data-align="center" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Generated on</th>
								<th data-field="operate" data-formatter="for_verification" data-events="operateEvents"  data-halign="center" data-align="center">Manage</th>
							</tr>
						</thead>
					</table>
					<?php if($verify){ ?>
						<a href="<?=HTTP_PATH.'budget/approve/reject/for_verification'?>">
							<button class="btn btn-sm btn-danger pull-right">Reject All</button>
						</a>
						<a href="<?=HTTP_PATH.'budget/approve/verified/for_verification'?>">
							<button class="btn btn-sm btn-success pull-right">Approve All</button>
						</a>
					<?php } ?>
				</div>
				<div id="forFinalApproval" class="tab-pane fade">
					<table data-toggle="table" id="for-approval-table" class="table table-bordered table-striped table-hover" data-url="<?php echo HTTP_PATH."budget/verify_budget_summary/for_approval"; ?>" data-cache="false" data-side-pagination="server" data-pagination="true" data-show-columns="true" data-page-list="[5, 10, 20, 50, 100, 200, 500, 1000, 2500, 5000, 10000]" data-search="true" data-strict-search="false">
						<thead>
							<tr>
								<th data-field="id" data-align="center" data-visible="false" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">ID</th>
								<th data-field="company" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Company</th>
								<th data-field="department" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Department</th>
								<th data-field="vessel" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Vessel</th>
								<th data-field="status" data-align="center" data-visible="false" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Status</th>
								<th data-field="final_amount" data-align="center" data-visible="false" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Total Amount</th>
								<th data-field="type" data-align="center" data-visible="false" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Type</th>
								<th data-field="year" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Year</th>
								<th data-field="generated_by" data-align="center" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Generated by</th>
								<th data-field="generated_on" data-align="center" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Generated on</th>
								<th data-field="operate" data-formatter="for_approval" data-events="operateEvents"  data-halign="center" data-align="center">Manage</th>
							</tr>
						</thead>
					</table>
					<?php if($approval){ ?>
						<a href="<?=HTTP_PATH.'budget/approve/reject/for_approval'?>">
							<button class="btn btn-sm btn-danger pull-right">Reject All</button>
						</a>
						<a href="<?=HTTP_PATH.'budget/approve/approved/for_approval'?>">
							<button class="btn btn-sm btn-success pull-right">Approve All</button>
						</a>
					<?php } ?>
				</div>
				<div id="approvedBudget" class="tab-pane fade">
					<table data-toggle="table" id="approved-table" class="table table-bordered table-striped table-hover" data-url="<?php echo HTTP_PATH."budget/verify_budget_summary/approved"; ?>" data-cache="false" data-side-pagination="server" data-pagination="true" data-show-columns="true" data-page-list="[5, 10, 20, 50, 100, 200, 500, 1000, 2500, 5000, 10000]" data-search="true" data-strict-search="false">
						<thead>
							<tr>
								<th data-field="id" data-align="center" data-visible="false" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">ID</th>
								<th data-field="company" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Company</th>
								<th data-field="department" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Department</th>
								<th data-field="vessel" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Vessel</th>
								<th data-field="status" data-align="center" data-visible="false" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Status</th>
								<th data-field="final_amount" data-align="center" data-visible="false" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Total Amount</th>
								<th data-field="type" data-align="center" data-visible="false" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Type</th>
								<th data-field="year" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Year</th>
								<th data-field="generated_by" data-align="center" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Generated by</th>
								<th data-field="generated_on" data-align="center" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Generated on</th>
								<th data-field="operate" data-formatter="approved" data-events="operateEvents"  data-halign="center" data-align="center">Manage</th>
							</tr>
						</thead>
					</table>
				</div>
				<!--div id="forPurchase" class="tab-pane fade">
					<h3></h3>
					<table data-toggle="table" class="table table-bordered table-striped table-hover" data-url="<?php echo HTTP_PATH."manager/verify_budget_summary"; ?>" data-cache="false" data-side-pagination="server" data-pagination="true">
						<thead>
							<tr>
								<th data-field="id" data-align="center" data-visible="false" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">ID</th>
								<th data-field="company" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Company</th>
								<th data-field="department" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Department</th>
								<th data-field="vessel" data-align="center" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Vessel</th>
								<th data-field="status" data-align="center" data-visible="false" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Status</th>
								<th data-field="final_amount" data-align="right" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Total Amount</th>
								<th data-field="year" data-align="center" data-visible="true" data-sortable="true" data-filter-control="input" data-filter-strict-search="false">Year</th>
								<th data-field="generator" data-align="center" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Generated by</th>
								<th data-field="generated_on" data-align="center" data-visible="true" data-sortable="true" data-filter-control="select" data-filter-strict-search="false">Generated on</th>
								<th data-field="operate" data-formatter="approved" data-events="operateEvents"  data-halign="center" data-align="center">Manage</th>
							</tr>
						</thead>
					</table>
					<br/>
				</div-->
			</div>
		</div>
	</div>
</div>

<script>

	function view(value, row, index) {
		return [
			'<a class="btn btn-danger btn-xs btn-block force-pageload" href="<?php echo HTTP_PATH.'budget/edit_percentage'; ?>/'+ row['id'] +'" data-toggle="modal" data-target="#modalDialogNorm" data-backdrop="static">Edit</a>'
		].join('');
	}
	$(function () {
		var $table = $('#percentage-table');
		$table.bootstrapTable();
	});

	function for_verification(value, row, index) {
		return [
			'<a class="btn btn-warning btn-xs btn-block force-pageload" href="<?php echo HTTP_PATH.'budget/verify_item_view'; ?>/'+ row['id'] +'" data-toggle="modal" data-target="#modalDialog" data-backdrop="static">View</a>'
		].join('');
	}
	$(function () {
		var $table = $('#for-verification-table');
		$table.bootstrapTable();
	});

	function for_approval(value, row, index) {
		return [
			'<a href="<?php echo HTTP_PATH.'budget/verify_item_view';?>/'+ row['id'] +'" data-toggle="modal" data-target="#modalDialog" data-backdrop="static" ><button class="btn btn-info btn-xs btn-block force-pageload">View</button></a>'
		].join('');
		//if($this->Abas->checkPermissions("manager|reports",false)):
	}
	$(function () {
		var $table = $('#for-approval-table');
		$table.bootstrapTable();
	});


	function approved(value, row, index) {
		return [
			'<a class="btn btn-success btn-xs btn-block force-pageload" href="<?php echo HTTP_PATH.'budget/verify_item_view/'; ?>'+ row['id'] +'" data-toggle="modal" data-target="#modalDialog" data-backdrop="static">View</a>'
		].join('');
	}
	$(function () {
		var $table = $('#approved-table');
		$table.bootstrapTable();
	});

</script>

