<?php
	$year = date('Y');
	$prev_year = $year - 1;
?>

<h2 id="glyphicons-glyphs">Annual Budget</h2>

<div class="panel-group" role="tablist" aria-multiselectable="true">
	<div class="panel panel-default">
		<div class="panel-body">
			<ul class="nav nav-tabs">
				<li class="nav-primary"><a data-toggle="tab" href="#forPurchase">For Purchase</a></li>
				<a href="<?php echo HTTP_PATH.'manager/set_increment'; ?>" data-toggle="modal" data-target="#modalDialogNorm" data-backdrop="static">
					<button class="btn btn-primary btn-sm pull-right">Set Increment</button>
				</a>
			</ul>
			<div class="tab-content">
				<div id="forPurchase" class="tab-pane fade">
					<?php 
						$account_type_array = array(
							'revenue' => 'Revenue',
							'cost_of_sales' => 'Cost of Sales',
							'operating_expenses' => 'Operating Expenses',
							'assets' => 'Assets',
							'liabilities' => 'Liabilities',
							'equity' => 'Equity'
						);
					?>
				
					<?php foreach ($account_type_array as $accountVar => $accountName) { ?>
						<?php if (isset(${$accountVar})) { ?>
							<h3><?=$accountName?></h3>
							<table class="table table-bordered table-striped table-hover">
								<thead>
									<tr>
										<th>ID</th>
										<th>Company</th>
										<th>Department</th>
										<th>Vessel</th>
										<th>Total Amount</th>
										<th>Year</th>
										<th>Generated by</th>
										<th>Generated on</th>
										<!--th data-field="operate" data-formatter="for_verification" data-events="operateEvents"  data-halign="center" data-align="center">Manage</th-->
									</tr>
								</thead>
								<tbody>
									<?php foreach (${$accountVar} as $ctr => $row) { ?>
										<tr>
												<td><?=$row['id']?></td>
												<td><?=$row['company']?></td>
												<td><?=$row['department']?></td>
												<td><?=$row['vessel']?></td>
												<td><?=$row['total_amount']?></td>
												<td><?=$row['year']?></td>
												<td><?=$row['generated_by']?></td>
												<td><?=$row['generated_on']?></td>
											
											<?php //$this->Mmm->debug($revenue_data)?>
										</tr>
									<?php } ?>
								</tbody>
							</table>
							<br/>
					<?php } 
				} ?>
				</div>
			</div>
		</div>
	</div>
</div>


