<?php
	$prev_year = date('Y') - 1;
?>
<div class="panel panel-primary">
	<div class="panel-heading">
		<h2 class="panel-title"><?=$company->name?>
			<button type="button" class="close" data-dismiss="modal">
				<span aria-hidden="true">×</span>
			</button>
		</h2>
	</div>
</div>
<div class="panel-body">
	<table id="percentage-table" class="table table-bordered table-striped table-hover" data-cache="false" data-pagination="true" data-show-columns="true" data-page-list="[5, 10, 20, 50, 100, 200, 500, 1000, 2500, 5000, 10000]" data-search="true" data-strict-search="false">
		<thead>
			<tr>
				<th>ID</th>
				<th>Department</th>
				<th>Debit</th>
				<th>Credit</th>
				<th>Status</th>
				<th>Generated by</th>
				<th>Date generated</th>
				<th data-visible="false">Verifier</th>
				<th data-visible="false">Approver</th>
				<!--th>Manage</th-->
			</tr>
			
		</thead>
		<tbody>
		<?php 
		if(isset($budget)){
		foreach($budget as $ctr => $row) { ?>
			<tr>
				<td><?=$row['id']?></td>
				<td><?=$row['department']?></td>
				<td style="text-align: right;"><?=number_format($row['debit'],2)?></td>
				<td style="text-align: right;"><?=number_format($row['credit'],2)?></td>
				<td><?=$row['status']?></td>
				<td><?=$row['generated_by']?></td>
				<td><?=$row['generated_on']?></td>
				<td><?=$row['verifier']?></td>
				<td><?=$row['approver']?></td>
				<!--td>
					<a href="<?=HTTP_PATH.'manager/add_account/'.$row['id']?>">
						<button class="btn btn-info btn-xs btn-block">view</button>
					</a>
				</td-->
			</tr>
		<?php } } ?>
		</tbody>

	</table>
	<script>
		$(document).ready(function () {
		  $('#percentage-table').bootstrapTable();
 		});
	</script>
	<button data-dismiss="modal" class="btn btn-danger btn-sm pull-right">Close</button>
</div>

					

